### ISSUE TITLE
Is it possible to recompile this php with new ssl library

### ISSUE THREAD

**Issue by concept47** [liip/php-osx#184] opened 2016-08-08 23:52 UTC
Essentially [I'm getting this error](http://stackoverflow.com/questions/26710482/yosemite-ssl-ca-certificate-set-but-certificate-verification-is-disabled) 

```
CA certificate set, but certificate verification is disabled
```

through php's Guzzle library when trying to connect to a secure url. 

Unfortunately it looks as if this PHP (I'm using 5.6) is compiled against Apple's openssl implementation which is causing the problem. [See this for more detail](http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error/26538127#26538127) ... 

the configure command says

```
'--with-openssl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/local
```

.. so it looks like the only way around this is to recompile against a new ssl

**Comment by chregu** [comment] 2017-05-05 22:24
Dupe of #175. Please try again, hopefully it's solved now

**Closed by chregu** 2017-05-05 22:24 UTC
