### ISSUE TITLE
cURL error on SSL: CA certificate set, but certificate verification is disabled

### ISSUE THREAD

**Issue by lgigon** [liip/php-osx#213] opened 2017-04-19 15:49 UTC
Got this error on SSL urls : CA certificate set, but certificate verification is disabled
It seems that cURL on that version is outdated The most recent stable version is 7.53.1, released on 24th of February 2017. Anything OLDER will cause this error.
How can we update cURL on php package?

**Comment by chregu** [comment] 2017-05-05 20:25
dupe of #175, will be fixed tonight with a new curl/openssl build

**Closed by chregu** 2017-05-05 20:25 UTC
